name: twasol
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk:  ">=2.17.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons:
  smooth_page_indicator:
  conditional_builder_null_safety:
  bloc:
  flutter_bloc:
  cubit:
  http:
  hexcolor:
  shared_preferences:
  fluttertoast:
  carousel_slider:
  firebase_core:
  firebase_auth:
  cloud_firestore:
  image_picker:
  firebase_storage:
  firebase_messaging: ^14.0.3
  desktop_window:
  responsive_builder:
  easy_splash_screen:
  intl:
  flutter_launcher_icons:
#  awesome_notifications:
  flutter_local_notifications:
  google_sign_in:
  pull_to_refresh:
  permission_handler: ^10.2.0
  record:
#  just_audio: ^0.9.20
#  audio_visualizer: ^0.1.1
  audioplayers:
  timezone:
  flutter_audio_waveforms:
#  social_media_recorder:


flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo.png"

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/


  fonts:
    - family: janna
      fonts:
        - asset: assets/fonts/janna.ttf
    - family: IconBroken
      fonts:
        - asset: assets/fonts/icons.ttf